name = "magnetic-builds"
main = ".open-next/worker.js"
compatibility_date = "2026-09-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "magnetic-builds-production"
database_id = "411dd993-894f-4625-bbef-af18523dd681"
migrations_dir = "drizzle"
