name = "magnetic-builds"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "DB"
database_name = "magnetic-builds-production"
database_id = "411dd993-894f-4625-bbef-af18523dd681"
migrations_dir = "drizzle"
